version: '3'
services:
  main:
    build: .
    volumes:
    - ./src:/home/src/
    entrypoint:
      - tail
      - -f
      - /dev/null
    cap_add:
      - SYS_PTRACE
    # security_opt:
    #   - seccomp
