version: '3'
services:
  main:
    image: mkusaka/compiler_env:2019-07-20
    volumes:
    - ./src:/home/src/
    entrypoint:
      - tail
      - -f
      - /dev/null
    cap_add:
      - SYS_PTRACE
    environment:
      - TERM=xterm-256color
    # security_opt:
    #   - seccomp
