version: 2
jobs:
  test:
    docker:
      - image: mkusaka/compiler_env:2019-05-14
    steps:
      - checkout
      - run:
          name: run test
          command: |
              cd src
              make test > result.txt
              cat result.txt
      - store_artifacts:
          path: ./src/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
